name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: '0 0 * * *' }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ['master', 'main'] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: WakaAPI
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ''
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_url: http://wakapi.dev
          plugin_wakatime_limit: 6
          plugin_wakatime_days: 365
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
